version: '3'

services:
  db:
    image: postgres:16.1-alpine
    container_name: driver_app_db_container
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./database_backup:/var/lib/postgresql/data
    tty: true
    environment:
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD=123456